version: "3.8"
services:
  kegerator:
    image: ${IMAGE}
    tty: true
    stdin_open: true
    privileged: true
    build:
      context: ${KEG_CONTEXT_PATH}
      dockerfile: ${KEG_DOCKER_FILE}
      args:
        - ENV
        - DOC_APP_PATH
        - DOC_CLI_PATH
        - DOC_CORE_PATH
        - DOC_COMPONENTS_PATH
        - DOC_RESOLVER_PATH
        - DOC_RETHEME_PATH
        - GIT_CLI_URL
        - GIT_CORE_URL
        - GIT_COMPONENTS_URL
        - GIT_KEY
        - GIT_RETHEME_URL
        - GIT_RESOLVER_URL
        - GIT_APP_URL
        - KEG_IMAGE_FROM
        - KEG_EXEC_CMD
        - KEG_NM_INSTALL
        - NODE_ENV
        - TAP
    container_name: ${CONTAINER_NAME}
    environment:
      - ENV
      - DOC_APP_PATH=/keg/tap
      - DOC_CLI_PATH=/keg/keg-cli
      - KEG_GLOBAL_CONFIG=/keg/.kegConfig/cli.config.json
      - GIT_CLI_URL
      - GIT_APP_URL
      - KEG_EXEC_CMD
      - KEG_NM_INSTALL
      - NODE_ENV
      - TAP
    ports:
      - ${EXPO_DEBUG_PORT}:${EXPO_DEBUG_PORT}
      - ${API_PORT}:${API_PORT}
      - ${SOCKET_PORT}:${SOCKET_PORT}
      - 80:${DOC_APP_PORT}
    volumes:
      - ${CLI_PATH}:/keg/keg-cli
