
env:
  # --- LOCAL ENV CONTEXT --- #
  COMPONENTS_PATH: "{{ cli.paths.components }}"
  RETHEME_PATH: "{{ cli.paths.retheme }}"
  RESOLVER_PATH: "{{ cli.paths.resolver }}"
  CLI_PATH: "{{ cli.paths.cli }}"
  KEG_CLI_GLOBAL: "/Users/lancetipton/.kegConfig"

  # --- DOCKER ENV CONTEXT --- #

  # Default location of the tap in the docker container
  DOC_APP_PATH: /keg/tap
  DOC_APP_PORT: 19006
  DOC_CORE_PATH: /keg/tap/node_modules/keg-core
  DOC_COMPONENTS_PATH: /keg/tap/node_modules/keg-core/node_modules/@simpleviewinc/keg-components
  DOC_RETHEME_PATH: /keg/tap/node_modules/keg-core/node_modules/@simpleviewinc/re-theme
  DOC_RESOLVER_PATH: /keg/tap/node_modules/keg-core/node_modules/@simpleviewinc/tap-resolver


  # --- GENERAL CONTEXT ENVs --- #

  # Image Build information
  IMAGE: kegerator
  VERSION: "0.0.1"
  CONTAINER_NAME: kegerator

  SOCKET_PORT: 9091
  API_PORT: 9090

  # Git tap url in github
  GIT_APP_URL: INITIAL
